baseURL = "https://kinkylaura.eu/"
languageCode = "en-us"
title = "Lauras Kinky Adventures"
theme = "archie"
copyright = "© Laura"
paginate = 3

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Hi I'm Laura and I'm a submissive blogging about my imagination! You can read more [about me](/about/) and about [my rules](/rules/) here"



[[params.social]]
name = "Fediverse"
icon = "mail"
url = "https://girlcock.club/@laura"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kinkylaura"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
