[[redirects]]
  from = "/limits"
  to = "https://bdsm-limits.com/#YYYYMYYYNNNYYYYNNNNNNYYYNYYYYYYYYYYCCYCYYCYCCYYYCYCYYCYYYYYYCCMNNCCMYYYYMNNNYNYCYCYYYYNNNNNCCCNNNNCNYNNNNNNNNYCYNYYYCYYMCYYYMYYMYNYYCYMYMYYMNNMNNNNYYYYYMYYNNNYCYYYCNYNMYCYNCNNN"
